name: Build and Push Docker Image to ECR # This is what shown on the Actions tab inside GitHub repository.

on: # Defines the event that triggers workflow.
  push:
    branches:
      - main # Automatically run this workflow every time code is pushed or merged into the main branch.
      - trial

permissions:
  id-token: write  # Grants GitHub permission to request a short-lived JWT from GitHub OIDC provider.
  contents: read # Gives the workflow permission to read and download repository source code.

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Tells GitHub to spin up a fresh, virtual Linux (Ubuntu) virtual machine hosted by GitHub to run these steps.

    steps: # list of commands to run sequentially inside the VM
      - name: Checkout Code # just a name as an indicator for reader
        uses: actions/checkout@v4 # official GitHub action to clone project's source code into the VM's working directory

        
      - name: Debug AWS Role ARN
        run: |
          curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | cut -d. -f2 | base64 -d 2>/dev/null | python3 -m json.tool
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}



      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4 # AWS's official GitHub action to authenticate
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }} # Fetches IAM Role ARN from GitHub Repository Variables and assumes that role temporarily via OIDC
          aws-region: ${{ vars.AWS_REGION }} # Fetches AWS region from GitHub Repository Variables to connect to

      - name: Log in to Amazon ECR
        id: login-ecr # Gives this step a name so the next step can reference its output
        uses: aws-actions/amazon-ecr-login@v2 # AWS's action to log the VM's local Docker daemon into private Amazon ECR registry

      - name: Build, Tag, and Push Image
        env: # Defines temporary environment variables for this specific step
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  # Reads the registry URL generated by previous Step (login-ecr).
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }} # Reads repository name from GitHub Variable
          IMAGE_TAG: ${{ github.sha }} # Git commit hash to ensure every single build gets a unique tag (e.g., a1b2c3d...).
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG